### PR TITLE
Switch from Fragment- to AppCompatActivities and add empty settings activity

### PR DESCRIPTION
**Pull request by N00bySumairu**

### CODE REVIEW

**Comment by CylonicRaider** [comment]
If we are to drop support for older Android versions, we should also clean out the related comments (like the one in `app/src/main/res/menu/actions_room.xml`).

In addition, getting Up navigation right in our situation is tricky as the settings activity has no definite parent — it could be either MainActivity or RoomActivity.

**Comment by N00bySumairu** [comment]
> If we are to drop support for older Android versions, we should also clean out the related comments (like the one in `app/src/main/res/menu/actions_room.xml`).

We are not dropping support for older Android versions, as far as I can tell. The only change here is moving away from Holo and the old Android theme before Holo, switching instead to the AppCompat theme. This means that the app will look as close as possible on old devices to how it does on modern devices. API support is unchanged.

> In addition, getting Up navigation right in our situation is tricky as the settings activity has no definite parent — it could be either MainActivity or RoomActivity.

I have also thought about that issue but opted to go with MainActivity as the sole parent activity and the only entry point to the SettingsActivity for now. This will need a do-over after resolving #1 anyways.

**Comment by N00bySumairu** [comment]
Ah, now I think I see what you mean. Your comment was regarding `app:showAsAction` / `android:showAsAction`, right?
I made that change because `android:showAsAction` seems to be ignored by AppCompat ActionBars, resulting in the Users Menu item always being hidden in the three-dot menu. Even without AppCompat ActionBars, using the native one, `android:showAsAction` did not seem to always be respected.
If this is alright with you I'd just remove the now outdated comment and stick with the AppCompat ActionBars.

**Comment by CylonicRaider** [comment]
> We are not dropping support for older Android versions, as far as I can tell.

Well... Since the latest release, we do. :wink: In any case, there's still some old code (and comments) left.

> This will need a do-over after resolving #1 anyways.

Not necessarily; the idea of #1 is to leave the UI of the room activity (almost) the same but to replace the currently active data structures when the user changes rooms.

> If this is alright with you I'd just remove the now outdated comment [...]

Yep.

**Comment by N00bySumairu** [comment]
There are two options for the up navigation / activity parent problem (at least as far as I can tell):

1. Abuse the up navigation and dynamically override [Activity::getParentActivityIntent](https://developer.android.com/reference/android/app/Activity#getParentActivityIntent()) to effectively achieve multiple / dynamic parent activities
2. Don't use up navigation at all, just rely on back navigation (which does work just fine)

**Pull request merged**
